######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 16 12:33:51 2008
######################################################################

TEMPLATE = app
TARGET = qoplot
DESTDIR=../out

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
 plotapp.h \
 op_com.h \
 mainwindow.h \
 command.h
SOURCES += \
	main.cpp \
 plotapp.cpp \
 op_com.cpp \
 mainwindow.cpp \
 command.cpp
FORMS += mainwindow.ui

